### ISSUE TITLE
Pandocに対応したsample.mdの更新

### ISSUE THREAD

**Issue by niszet** [YoshiRi/MarkdownToAsciidoc#1]
ブログでコメントした者です。Pandocでのadocへの変換について、いくつかはmarkdown側の書き方の問題と思われる箇所があったため、sample.mdを更新したものを後ほどPR出しますので、ご参考になればと思います。

PRには変換したsample_pandoc.adocも含めています。本commitではsample.mdに対して以下の対応をしています。

* インラインのCode、`...`について前後に半角空白を入れています。
* <>は自動でリンクとみなされるため、例示箇所は\<..\>としています。
* 定義参照リンクは2つの[]の間に空白を入れると認識されないため、これを詰めています。

また、以下はPandoc側の問題であることが分かっており、ファイルやオプションの変更では対応できないとみています。

* 番号付きリストは基本的に[arabic]が自動でつくので記号にはならない（これは現状でも対応できるかもしれませんが、調査不足）
* Pandocで出力するadoc形式にはhtmlは埋め込められないため、`<s>`タグなどは対応できないです。
* ハイフンの並びは他の記法とぶつかることが多いので、使用を推奨しません（sample.mdはこれを修正していません）
* ネストしたBlockQuoteはPandoc側に問題があり対応できていません（問題個所は把握しました）
* h1レベルが`--shift-heading-level-by=-1`すると消え、titleとしても保存されない

変換に使用したコマンドは以下のとおりです。

```
pandoc sample.md -o sample_pandoc.adoc  --shift-heading-level-by=-1
asciidoctor sample_pandoc.adoc 
```

使用したPandocのバージョンは、

```
> pandoc --version
pandoc 2.11
Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10.0.2
```

asciidoctor のバージョンは

```
> asciidoctor --version
Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```
です。

**Comment by YoshiRi** [comment]
sampleの更新ありがとうございます。
後ほどKramdocでも確認して比較してみてみます。
